    units real
    atom_style full
    pair_style hybrid lj/cut 10.0 eam/fs lj/charmm/coul/long 9.0 10.0 10.0 
    # Default styles and settings for AMBER based force-fields:
    bond_style      hybrid harmonic
    angle_style     hybrid harmonic
    dihedral_style  hybrid fourier
    #improper_style  hybrid cvff
    kspace_style    pppm 0.0001
    #pair_modify     shift yes
    pair_modify     mix arithmetic
    special_bonds   amber
